CREATE DATABASE IF NOT EXISTS ecom_user_db;
CREATE DATABASE IF NOT EXISTS ecom_product_db;
CREATE DATABASE IF NOT EXISTS ecom_order_db;
CREATE DATABASE IF NOT EXISTS ecom_inventory_db;
CREATE DATABASE IF NOT EXISTS ecom_payment_db;
